[package]
name = "names-generator2"
version = "0.3.0"
edition = "2024"
license-file = "LICENSE"
description = "A sensible and sufficiently random funny animal names generator"
repository = "https://github.com/Peppy-bot/names-generator"

[dependencies]
rand_core = { version = "0.10", default-features = false }

[dev-dependencies]
rand = "0.10"
